#!/bin/bash

jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            dask-labextension@3.0.0 \
                            @pyviz/jupyterlab_pyviz \
                            jupyterlab-nvdashboard

#EOF
