#!/usr/bin/env python
"""
Runs beam-boot when called with beam-boot parameters,
or acts like empty
"""
import os
import sys

REQUIRED_BEAM_BOOT_PARAMS = [
    '-id', '-control_endpoint', '-logging_endpoint',
    'artifact_endpoint', 'provision_endpoint'
]
if all(x in sys.argv for x in REQUIRED_BEAM_BOOT_PARAMS):
    command = '/usr/local/bin/boot'
    args = sys.argv[1:]
else:
    command = sys.argv[1]
    args = sys.argv[2:]

os.execvp(command, args)