#!/bin/bash

jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            @jupyterlab/geojson-extension \
                            dask-labextension@3.0.0 \
                            @pyviz/jupyterlab_pyviz \
                            jupyter-leaflet

#EOF
