#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export PANGEO_ENV="base"
if [[ -z "${PANGEO_SCRATCH_PROTOCOL}" ]]; then
    :
else
    export PANGEO_SCRATCH="${PANGEO_SCRATCH_PROTOCOL}://pangeo-scratch/${JUPYTERHUB_USERNAME}/"
fi

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
