# Note: this environment will be merged with the pangeo-notebook/environment.yml
# by conda-lock. Only put things here that are not already in pangeo-notebook
name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cuda-version>=13.0
  - jupyterlab-nvdashboard
  - gpytorch
  - pytorch>=2.10.0=cuda13*
  - torchvision>=0.26.0=cuda13*
  - torchgeo
